"""Shared enums and limits (TZ §5–6)."""

CAMPAIGN_TYPE_MVP = 9
MAX_BID_KOPECKS_DEFAULT = 150_000  # 1500 ₽
MIN_SHOWS_FOR_MANAGED = 100
MIN_TEST_HOURS_DEFAULT = 2

PROMOTION_PAUSE_SEC = 1.2
FULLSTATS_PAUSE_SEC = 7.0

PENDING_NM_PREFIX = "PENDING_"
